### ISSUE TITLE
Questions to ask

### ISSUE THREAD

**Issue by Ahhhh-man** [engineering89-job-project-group-2/project#10]
* What do you mean 'Bespoke calls for specific job role data'?
* What info do you need about each job?
* In current scope, what further services should we expand to?
* Create a connected database for full deployment ??????????
* How should we implement vagrant in the project?
*

**Comment by monotiller** [comment]
-    Can see certain data – etc top 5, 10, 12 etc, or by job filter – DevOps, front end etc. use search option
-    Everything from ITJobswatch, use API
-    User should be able to login, and see more than a guest, upload cv
-    Database can be csv/sql
-    Sqlite will only need one machine
-    vagrant up will put site online
-    Login as employer/admin and advertise
-    Login as user to search for job
