### ISSUE TITLE
Wire Frame diagram

### ISSUE THREAD

**Issue by Ahhhh-man** [engineering89-job-project-group-2/project#12]
Pages we need to make wireframes of:
- [x] Job search page
- [x] Recruiter view
- [x] Login page
- [x] Register page
- [x] Home page

(https://wireframe.cc/pro/pp/3759df283458481)
[Wireframe website](https://wireframe.cc/)

**Comment by NikiNikiforidi** [comment]
Draft Wireframe
![Home](https://user-images.githubusercontent.com/86292184/126153034-122d4a7c-eeb4-4670-ac18-aa8357dd710a.PNG)
![Roles](https://user-images.githubusercontent.com/86292184/126153036-f7a7ab7c-b895-4d24-967f-8f7d10684a9d.PNG)
![Register](https://user-images.githubusercontent.com/86292184/126153039-950c9851-d6e7-4268-b520-f242cc97f53c.PNG)
![login](https://user-images.githubusercontent.com/86292184/126153041-13a15ff9-3c92-4990-8145-bf0188d468f2.PNG)
![vacancies](https://user-images.githubusercontent.com/86292184/126153044-3f63d251-fefc-4f8a-9466-d68efb129e8e.PNG)
